version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: underexp0
    ports:
      - 5666:5432

  # adminer:
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "underexpo@email.com"
  #     PGADMIN_DEFAULT_PASSWORD: "underexp0"
  #   ports:
  #     - "8666:80"
  #   depends_on:
  #     - db
